### ISSUE TITLE
Feature-Request: PGP-encrypt game_state.json via GitHub-Secret

### ISSUE THREAD

**Issue by ADoebeling** [agonyz/agonyz#154]
Moin Frank / @agonyz,

über [game_state.json](https://raw.githubusercontent.com/agonyz/agonyz/main/data/game_state.json) kann man aktuell etwas zu einfach cheaten.
Hast Du mal darüber nachgedacht ein [Github-Secret](https://docs.github.com/de/actions/security-guides/using-secrets-in-github-actions) zu erstellen, über das Du das File pgp-verschlüsselst?

Glaube das wäre eine sehr cleane Lösung und cheaten wird deutlich schwerer ;-)

Grüße
Andreas.

**Comment by agonyz** [comment]
Hi @ADoebeling, 

da hast Du natürlich recht. Bisher hatte ich einfach auf die guten Absichten im Bezug auf ehrliche Spielweise der Menschen vertraut :D 

Coole Idee, habe ich gleich mal umgesetzt: https://github.com/agonyz/agonyz/pull/170/commits/c27573f8c6a1011f4dc7381fed33cf648c3d4030

Darfst gerne weiter die Spieltabelle anführen, wenngleich es nun auch etwas schwerer sein dürfte :)

Gruß
Frank.

**Comment by agonyz** [comment]
> Sehr cool! :) Schönen Abend

Dankeschön, Dir auch (Und immer her mit Ideen jeglicher Art, wenn du welche hast :))
